ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_recurring       BOOLEAN     NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_pattern VARCHAR(20);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_end_date TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS template_id         UUID;
